#! /bin/sh
# BSPWM config file

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6

# rule feh                            state=floating

bspc config window_gap 25
bspc config split_ratio 0.50
bspc config border_width 0

polybar -c ~/.config/polybar/mainbar.ini -r &
nitrogen --set-zoom-fill ".config/nitrogen/background.png" &
picom --experimental-backend --config ~/.config/picom/picom.conf &
